---
name: mypy

"on":
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Running mypy
        run: |
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run mypy --strict check_goodwe tests/
