---
name: pylint

"on":
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Running tests
        run: |
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run ruff check check_goodwe/ tests/
